### ISSUE TITLE
singularity recipe

### ISSUE THREAD

**Issue by gsiegwald** [grst/containerize-conda#1]
Hi Gregor,
What should be inside the "Singularity" recipe file to be able to build the image with the command 
`singularity build --fakeroot <OUTPUT_CONTAINER.sif> Singularity`?
Thanks

**Comment by grst** [comment]
this one ;) 
https://github.com/grst/containerize-conda/blob/master/Singularity

**Comment by gsiegwald** [comment]
haha thank I didn't see it
