### ISSUE TITLE
Singularity container still using original system's conda env

### ISSUE THREAD

**Issue by TimothyStephens** [grst/containerize-conda#7]
Hi,

Thanks for the awesome tool. 
Not sure if this is a bug or a result from my implementation of your code.

I noticed that if the version of conda that the container was built from is located anywhere in the home directory, then the container version of the code will become masked once the system's home directory is mounted during container initialization. 
This results in the container conda env no longer being accessible if you change systems, or the container running the original conda env outside the container if its the same system. 
My workaround was to use root permissions to install conda in `/opt/`
Since this directory isn't mounted automatically, we don't have issues with it being masked when the container is run.

Not sure their is an easy fix for this for non-root users since you would have to prevent mounting of the home directory, which is probably not an option for most users for various reasons.

Thanks.

**Comment by grst** [comment]
> Not sure their is an easy fix for this for non-root users since you would have to prevent mounting of the home directory, which is probably not an option for most users for various reasons.

I think you should always run singularity with `--no-home` for reproducibility reasons and just mount the directories you really need. This has also come up in the context of nextflow pipelines, see https://github.com/nextflow-io/nextflow/issues/2348

**Comment by TimothyStephens** [comment]
Thanks for the quick reply and the helpful link. 
I was unaware of the `--no-home` flag, but that perfectly addresses my problem.

Thanks.
